definitions:
  server.fullTransactionRequest:
    properties:
      currency:
        type: string
      quantity:
        type: number
      transactionCode:
        type: string
      transactionDate:
        type: string
      transmitter:
        type: string
    required:
    - currency
    - quantity
    - transactionCode
    - transactionDate
    - transmitter
    type: object
  web.ApiResponse:
    properties:
      code:
        type: integer
      data: {}
      error:
        type: string
    type: object
info:
  contact:
    email: daniel.medina@mercadolibre.com
    name: Daniel Medina
    url: http://github.com/dmedinao1
  description: Servicios para crear, listar, actualizar y eliminar transacciones.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Mercado libre bootcamp | Transacciones API
  version: "1.0"
paths:
  /transacciones:
    get:
      consumes:
      - application/json
      description: Obtiene todas las transacciones
      parameters:
      - description: Token de autorización
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Objeto con la lista de transacciones encontradas
          schema:
            $ref: '#/definitions/web.ApiResponse'
        "500":
          description: Error interno de la aplicación
          schema:
            $ref: '#/definitions/web.ApiResponse'
      summary: Obtiene todas las transacciones
  /transacciones/{id}:
    post:
      consumes:
      - application/json
      description: Reemplaza la transacción
      parameters:
      - description: Token de autorización
        in: header
        name: token
        required: true
        type: string
      - description: Id de la transacción a reemplazar
        in: path
        name: id
        required: true
        type: integer
      - description: Transacción a reemplazar
        in: body
        name: transacción
        required: true
        schema:
          $ref: '#/definitions/server.fullTransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Objeto con la transacción reemplazada
          schema:
            $ref: '#/definitions/web.ApiResponse'
        "400":
          description: Parámetros de entrada inválidos
          schema:
            $ref: '#/definitions/web.ApiResponse'
        "404":
          description: Transacción no encontrada
          schema:
            $ref: '#/definitions/web.ApiResponse'
        "500":
          description: Error interno de la aplicación
          schema:
            $ref: '#/definitions/web.ApiResponse'
      summary: Reemplaza una transacción ya creada por datos nuevos
swagger: "2.0"
